version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - '.:/app'
      - /usr/src/app/node_modules
    ports:
      - 3002:3000