version: "3.8"

services:
  sait-front:
    container_name: sait-front
    image: sait-front:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3002:3000