export {default as LoginPage} from './LoginPage'
export {default as RegisterIncident} from './RegisterIncident'
export {default as TechnicianAssigment} from './TechnicianAssigment'
export {default as Users} from './Users'
export {default as Incidences} from './Incidences'