export {default as RegisterIncident} from './RegisterIncident'
export {default as TechnicianAssigment} from './TechnicianAssigment'
export {default as Profiles} from './Profiles'
export {default as Incidences} from './Incidences'
export {default as Devices} from './Devices'
export {default as Components} from './Components'