export {default as RegisterIncident} from './RegisterIncident'
export {default as Technicians} from './Technicians'
export {default as Users} from './Users'
export {default as Incidences} from './Incidences'
export {default as Devices} from './Devices'
export {default as Components} from './Components'